# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://predmach.github.io/fastai_explore/"

git_url = "https://github.com/predmach/fastai_explore/tree/master/"

def custom_doc_links(name): return None
